<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset=<?= APP_CHARSET ?> >
        <title>RAW MATERIALS</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">



        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>

        <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
        <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
        <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">

        <script src="https://kit.fontawesome.com/1b24758128.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <?php View::content() ?>
    </body>
</html>
